<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WDD330 Portfolio</title>
    <link href="../styles/styles.css" rel="stylesheet" type="text/css">
    <link href="styles/week5.css" rel="stylesheet" type="text/css">
</head>

<body>
    <nav>
        <ul>
        </ul>
    </nav>
    <h1>Week 5 Notes:</h1>
    <p>
        This week the reading was about debugging and how can Javascript be used 
        for debugging and handling exceptions.
    </p>
    <h1>Code Example:</h1>
    <p>
        I found an example that tries a functionto multiply with a catch statement. The function is tested
        in the console.
    </p>

    <p>
        <script>
            class MultiplicatorUnitFailure extends Error {}

            function primitiveMultiply(a, b) {
                if (Math.random() < 0.2) {
                    return a * b;
                } else {
                    throw new MultiplicatorUnitFailure("Klunk");
                }
            }

            function reliableMultiply(a, b) {
                for (;;) {
                    try {
                        return primitiveMultiply(a, b);
                    } catch (e) {
                        if (!(e instanceof MultiplicatorUnitFailure))
                            throw e;
                    }
                }
            }

            console.log(reliableMultiply(8, 8));
            // â†’ 64
        </script>
    </p>
    <script src="../scripts/index.js"></script>
    <script src="scripts/week5.js" type="module"></script>
</body>

</html>